fix: issues with cloud foundry deploy scripts to follow best practices
konveyor/move2kube-demos pull request #179
Opened 2022-05-27 21:18 UTC by HarikrishnanBalagopal

2022-05-28 10:23 UTC, ashokponkumar requested changes
Few suggestions...

2022-05-28 10:23 UTC, ashokponkumar commented on samples/enterprise-app/src/deploy-to-cf.sh
> +cd "$working_dir"/gateway || exit # If the user presses ctrl-c during previous step it will take to the $working_dir
We can avoid the m2k demo prefix

2022-05-28 10:23 UTC, ashokponkumar commented on samples/enterprise-app/src/deploy-to-cf.sh
> +CF_STAGING_TIMEOUT=30 $CF_CLI_TOOL push "$appname"-frontend --var M2K_DEMO_GATEWAY_URL="http://$appname-gateway.mybluemix.net"
Lets avoid the m2k demo prefix

2022-05-30 07:10 UTC, Akash-Nayak requested changes
Lets also update the instructions related to manual CF deployment in the README files of the gateway and frontend services.
https://github.com/HarikrishnanBalagopal/move2kube-demos/tree/fix/scripts/samples/enterprise-app/src/gateway#deploying-to-cloud-foundry 
https://github.com/HarikrishnanBalagopal/move2kube-demos/tree/fix/scripts/samples/enterprise-app/src/frontend#deploying-to-cloud-foundry

2022-05-30 09:19 UTC, HarikrishnanBalagopal commented on samples/enterprise-app/src/deploy-to-cf.sh
> +app='enterprise-app'
to avoid parameter expansion

2022-05-30 09:20 UTC, HarikrishnanBalagopal commented on samples/enterprise-app/src/deploy-to-cf.sh
> +cd "$working_dir"/gateway || exit # If the user presses ctrl-c during previous step it will take to the $working_dir
done

2022-05-30 09:20 UTC, HarikrishnanBalagopal commented on samples/enterprise-app/src/deploy-to-cf.sh
> +CF_STAGING_TIMEOUT=30 $CF_CLI_TOOL push "$appname"-frontend --var M2K_DEMO_GATEWAY_URL="http://$appname-gateway.mybluemix.net"
done

2022-05-30 10:32 UTC, Akash-Nayak requested changes

2022-05-30 10:32 UTC, Akash-Nayak commented on samples/enterprise-app/src/deploy-to-ibmcloud-cf.sh
> +CF_CLI_TOOL='ibmcloud cf' ./deploy-to-cf.sh
@HarikrishnanBalagopal, I have tested the deploy-to-ibmcloud-cf.sh script on zsh, it's working fine. But, when I run `echo $appname` after running the script, it returns blank. Can you change it to `CF_CLI_TOOL='ibmcloud cf' source deploy-to-cf.sh` and check if the $appname value is accessible after the running the script?

2022-05-30 10:59 UTC, HarikrishnanBalagopal commented on samples/enterprise-app/src/deploy-to-ibmcloud-cf.sh
> +CF_CLI_TOOL='ibmcloud cf' ./deploy-to-cf.sh
> Lets also update the instructions related to manual CF deployment in the README files of the gateway and frontend services. https://github.com/HarikrishnanBalagopal/move2kube-demos/tree/fix/scripts/samples/enterprise-app/src/gateway#deploying-to-cloud-foundry https://github.com/HarikrishnanBalagopal/move2kube-demos/tree/fix/scripts/samples/enterprise-app/src/frontend#deploying-to-cloud-foundry

done

2022-05-30 11:00 UTC, HarikrishnanBalagopal commented on samples/enterprise-app/src/deploy-to-ibmcloud-cf.sh
> +CF_CLI_TOOL='ibmcloud cf' ./deploy-to-cf.sh
> @HarikrishnanBalagopal, I have tested the deploy-to-ibmcloud-cf.sh script on zsh, it's working fine. But, when I run `echo $appname` after running the script, it returns blank. Can you change it to `CF_CLI_TOOL='ibmcloud cf' source deploy-to-cf.sh` and check if the $appname value is accessible after the running the script?

That's on purpose. We don't want to pollute the global namespace with all our variables.
We do print the app name several times and also print the full urls to access the services and the website.

2022-05-30 11:03 UTC, HarikrishnanBalagopal commented on samples/enterprise-app/src/deploy-to-ibmcloud-cf.sh
> +CF_CLI_TOOL='ibmcloud cf' ./deploy-to-cf.sh
Also if we use `source` then anything declared in the terminal can affect the script as well.

2022-05-30 11:16 UTC, ashokponkumar approved these changes

2022-05-30 11:37 UTC, Akash-Nayak commented on samples/enterprise-app/src/deploy-to-ibmcloud-cf.sh
> +CF_CLI_TOOL='ibmcloud cf' ./deploy-to-cf.sh
Sure.

2022-05-30 11:42 UTC, Akash-Nayak commented on samples/enterprise-app/src/frontend/README.md
> +1. Using the same `$appname` that was used to deploy the backend and `gateway` services, run the below commands to deploy the `frontend` service to Cloud Foundry.
LGTM. One small suggestion. Can you change `run the below commands` to `run the below command`.

2022-05-30 11:46 UTC, HarikrishnanBalagopal commented on samples/enterprise-app/src/frontend/README.md
> +1. Using the same `$appname` that was used to deploy the backend and `gateway` services, run the below commands to deploy the `frontend` service to Cloud Foundry.
done

2022-05-30 11:47 UTC, Akash-Nayak approved these changes

2022-05-30 11:48 UTC, Akash-Nayak commented on samples/enterprise-app/src/frontend/README.md
> +1. Using the same `$appname` that was used to deploy the backend and `gateway` services, run the below commands to deploy the `frontend` service to Cloud Foundry.
Thanks Hari.. Nice work!

2022-05-30 11:50 UTC, merged