fix: Resolve port 80 permission denied issue on OpenShift cluster for docker-compose sample
konveyor/move2kube-demos pull request #228
Opened 2023-01-17 06:34 UTC by Akash-Nayak

<img width="1504" alt="Screenshot 2023-01-17 at 11 57 34 AM" src="https://user-images.githubusercontent.com/14867323/212825366-bd0b418f-b46b-4aae-a069-175291ef1d1e.png">

After fixing the port issue. 

<img width="1487" alt="Screenshot 2023-01-17 at 12 02 13 PM" src="https://user-images.githubusercontent.com/14867323/212826072-9b03369b-729d-4deb-b28d-a57efb54493a.png">

Signed-off-by: Akash Nayak <akash19nayak@gmail.com>

2023-01-17 06:36 UTC, ashokponkumar requested changes

2023-01-17 06:36 UTC, ashokponkumar commented on samples/docker-compose/multiple-services/web/site.conf
> +Listen 8082
Why not use 8080 port, that will feel standard.

2023-01-17 06:37 UTC, Akash-Nayak commented on samples/docker-compose/multiple-services/web/site.conf
> +Listen 8082
Yes sure, I will test it once and update the PR.

2023-01-17 07:00 UTC, Akash-Nayak commented on samples/docker-compose/multiple-services/web/site.conf
> +Listen 8082
I think I used port 8082 because there was some issue with 8080 port. `Address already in use; could not bind to address 0.0.0.0:8080`

<img width="832" alt="port 8080 address already in use" src="https://user-images.githubusercontent.com/14867323/212828648-62b5027d-78e2-4999-874d-65cea883c72b.png">

2023-01-17 09:25 UTC, HarikrishnanBalagopal requested changes

2023-01-17 09:25 UTC, HarikrishnanBalagopal commented on samples/docker-compose/multiple-services/web/Dockerfile
> +FROM registry.access.redhat.com/ubi8/php-74:latest
Try to use the docker hub image because it's more popular.
Should be able to just change the port number and run on Openshift.

2023-01-18 12:26 UTC, Akash-Nayak commented on samples/docker-compose/multiple-services/web/site.conf
> +Listen 8082
Yes, it fails to even running locally with `registry.access.redhat.com/ubi8/php-74:latest` image with 8080 port.
```docker run --rm -it -p 8080:8080 quay.io/akashnayak/fibonacci-web:latest
(98)Address already in use: AH00072: make_sock: could not bind to address 0.0.0.0:8080
no listening sockets available, shutting down
AH00015: Unable to open logs
```

2023-01-18 12:26 UTC, Akash-Nayak commented on samples/docker-compose/multiple-services/web/Dockerfile
> +FROM registry.access.redhat.com/ubi8/php-74:latest
I have changed it back to docker hub `php:7-apache` image,  it still wasn't able to run on Openshift with port 8080 just by changing the port number. As it was still trying to bind to port 80.

<img width="1488" alt="Screenshot 2023-01-18 at 5 49 20 PM" src="https://user-images.githubusercontent.com/14867323/213169742-22a968f8-4bfc-4e10-ad30-6f8e14d87b36.png">

For the `registry.access.redhat.com/ubi8/php-74:latest` image it is required to update the port in `/etc/httpd/conf.d/` file, but that doesn't work with the `php:7-apache` image.

It worked with the `php:7-apache` image after I add this line to the Dockerfile to change the port number in two `.conf` files.

```console
RUN sed -i 's/80/8080/g' /etc/apache2/sites-available/000-default.conf /etc/apache2/ports.conf
```

<img width="1500" alt="Screenshot 2023-01-18 at 5 54 33 PM" src="https://user-images.githubusercontent.com/14867323/213170749-6171d629-b4d1-4c16-bf4a-7eb2ca979e9d.png">

2023-01-18 12:27 UTC, Akash-Nayak commented on samples/docker-compose/multiple-services/web/site.conf
> +Listen 8082
https://github.com/konveyor/move2kube-demos/pull/228#discussion_r1073469763

2023-01-18 15:25 UTC, HarikrishnanBalagopal approved these changes
Thanks for keeping the base image

2023-01-18 15:34 UTC, ashokponkumar requested changes

2023-01-18 15:34 UTC, ashokponkumar commented on samples/docker-compose/multiple-services/web/Dockerfile
> +RUN sed -i 's/80/8080/g' /etc/apache2/sites-available/000-default.conf /etc/apache2/ports.conf
This will look like a very weird example, isn't it?

2023-01-18 18:04 UTC, Akash-Nayak commented on samples/docker-compose/multiple-services/web/Dockerfile
> +RUN sed -i 's/80/8080/g' /etc/apache2/sites-available/000-default.conf /etc/apache2/ports.conf
Yes, I also completely agree with that it looks weird. But, I have seen similar proposed solutions in some of the Git issues https://github.com/docker-library/php/issues/94#issuecomment-320695125, https://github.com/docker-library/php/pull/190#issuecomment-291972238.

The other possible solution I think would be to have a `conf` folder containing the two .conf files and use the COPY command to copy them to their respective locations (`/etc/apache2/sites-available/000-default.conf` and `/etc/apache2/ports.conf`) for using 8080 port with `php:7-apache` image. Or, we can use `registry.access.redhat.com/ubi8/php-74:latest` with some port other than 80/8080 and a single .conf file will be required to be copied `/etc/httpd/conf.d/` like the [previous commit](https://github.com/konveyor/move2kube-demos/pull/228/commits/2c7c8f58bc3843fed860ed34b751f2483a297e42) in this PR.

2023-01-31 06:52 UTC, ashokponkumar approved these changes

2023-01-31 06:52 UTC, merged